### ISSUE TITLE
REST endpoint for search

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/charles-github-ejb#101]
REST endpoint for search with pagination, using the AWS sdk to sign requests to amazon

**Comment by amihaiemil** [comment]
@charlesmike hello

**Comment by charlesmike** [comment]
> @charlesmike hello

Hi, @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format `owner.github.io` (or has a `gh-pages` branch) and the command is given by the repo's owner.

**Comment by amihaiemil** [comment]
@charlesmike hello

**Comment by charlesmike** [comment]
> @charlesmike hello

Hi, @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format `owner.github.io` (or has a `gh-pages` branch) and the command is given by the repo's owner.

**Comment by amihaiemil** [comment]
@charlesmike how's the new architecture?

**Comment by charlesmike** [comment]
> @charlesmike how's the new architecture?

@amihaiemil sorry I do not understand you. See [this link](http://charles.amihaiemil.com/doc.html#commands) for more details.

**Comment by amihaiemil** [comment]
@charlesmike hello there

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike hello there

Hi, @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format `owner.github.io` (or has a `gh-pages` branch) and the command is given by the repo's owner.

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by amihaiemil** [comment]
some other comment addressed to someone else

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly.

**Comment by amihaiemil** [comment]
@charlesmike hi there

**Comment by charlesmike** [comment]
> @charlesmike hi there

Hi, @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format `owner.github.io` (or has a `gh-pages` branch) and the command is given by the repo's owner.

**Comment by amihaiemil** [comment]
@charlesmike online?

**Comment by charlesmike** [comment]
> @charlesmike online?

@amihaiemil sorry I do not understand you. See [this link](http://charles.amihaiemil.com/doc.html#commands) for more details.

**Comment by amihaiemil** [comment]
@charlesmike hello there

**Comment by charlesmike** [comment]
> @charlesmike hello there

Hi, @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format `owner.github.io` (or has a `gh-pages` branch) and the command is given by the repo's owner.

**Comment by amihaiemil** [comment]
@charlesmike hello

**Comment by charlesmike** [comment]
> @charlesmike hello

Hi, @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format `owner.github.io` (or has a `gh-pages` branch) and the command is given by the repo's owner.

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly.

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil Some steps failed when precessing your command. See [logs](http://ec2-54-68-83-8.us-west-2.compute.amazonaws.com:8080/charles-rest/api/logs/Action_9aef715f-b2f5-4642-9a82-19f072406550.log) for details.

**Comment by amihaiemil** [comment]
@charlesmike hello

**Comment by charlesmike** [comment]
> @charlesmike hello

Hi, @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format `owner.github.io` (or has a `gh-pages` branch) and the command is given by the repo's owner.

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil the repository must not be a fork, you must own this repository.

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil the repository must not be a fork, you must own this repository.

**Comment by amihaiemil** [comment]
@charlesmike hi there

**Comment by charlesmike** [comment]
> @charlesmike hi there

Hi, @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format `owner.github.io` (or has a `gh-pages` branch) and the command is given by the repo's owner.

**Comment by amihaiemil** [comment]
done
