### ISSUE TITLE
Pull out notification checker in the EJB

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/charles-github-ejb#102]
In the current architecture the Github notification scheduler is inside the ejb jar, which comes as a dependency in the war. 

This **coupling** works fine if there is a single server, but if you deploy it on more nodes for load balancing then it's not ok - the scheduler will run in the same time from all the nodes, which does not make sense. Different java ee web servers solve this in all sorts of ways, but we shouldn't let this by itself.

To solve this issue, we need to:

1) pull out the notification checker, which will be deployed **alone** in a single server. It will check for notifications and it will send them via a HTTP post to an endpoint exposed by `charles-rest`.  This endpoint will be secured with a token known by the 2 parties (set as a sys property)

2) All the other classes and logic which are currently in `charles-github-ejb` will go in `charles-rest` and the ejb does not have to be a dependency anymore. 

So we will have 2 separate deployables: the `ejb checker jar` **going alone on a single server** and `charles-rest` which listens for POST notifications and performs the Action logic - this can go in a cluster without worries.

**Comment by amihaiemil** [comment]
@charlesmike hi

**Comment by charlesmike** [comment]
> @charlesmike hi

Hi, @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format ``owner.github.io`` (or has a ``gh-pages`` branch) and the command is given by the repo's owner.

**Comment by amihaiemil** [comment]
@charlesmike hello

**Comment by charlesmike** [comment]
> @charlesmike hello

Hi, @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format `owner.github.io` (or has a `gh-pages` branch) and the command is given by the repo's owner.

**Comment by amihaiemil** [comment]
@charlesmike some notification here!!

**Comment by amihaiemil** [comment]
test here

**Comment by charlesmike** [comment]
> @charlesmike some notification here!!

@amihaiemil sorry I do not understand you. See [this link](http://charles.amihaiemil.com/doc.html#commands) for more details.

**Comment by amihaiemil** [comment]
@charlesmike hi

**Comment by charlesmike** [comment]
> @charlesmike hi

Hi, @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format `owner.github.io` (or has a `gh-pages` branch) and the command is given by the repo's owner.

**Comment by amihaiemil** [comment]
done
