### ISSUE TITLE
Methods which have cached answers for Command

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/charles-github-ejb#109]
[Command](https://github.com/amihaiemil/charles-github-ejb/blob/master/charles-rest/src/main/java/com/amihaiemil/charles/github/Command.java) should have methods that cache their results before returning/check the cache before making an http call to Github's API.

This would greatly refactor the code. E.g. method `repo() : JsonObject` is necessary to get rid of the DTO JsonObject repo which is currently passed around (along with the Command) to save method calls.

**Comment by amihaiemil** [comment]
@charlesmike hi

**Comment by amihaiemil** [comment]
@charlesmike hello

**Comment by charlesmike** [comment]
> @charlesmike hello

Hi, @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format `owner.github.io` (or has a `gh-pages` branch) and the command is given by the repo's owner.

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by amihaiemil** [comment]
@charlesmike hello

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly.

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil Some steps failed when precessing your command. See [logs](http://ec2-54-68-83-8.us-west-2.compute.amazonaws.com:8080/charles-rest/api/logs/Action_ac6e0fcc-53e7-4ff1-b247-2b10382614a4.log) for details.

**Comment by amihaiemil** [comment]
@charlesmike hello

**Comment by charlesmike** [comment]
> @charlesmike hello

Hi, @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format `owner.github.io` (or has a `gh-pages` branch) and the command is given by the repo's owner.

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly.

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil Some steps failed when precessing your command. See [logs](http://ec2-54-68-83-8.us-west-2.compute.amazonaws.com:8080/charles-rest/api/logs/Action_58483c5f-06ce-4444-ad14-f0ff500de0a3.log) for details.

**Comment by amihaiemil** [comment]
@charlesmike pls index [this](http://www.amihaiemil.com/rest/2016/06/03/using-google-recaptha-with-jax-rs.html) page

**Comment by charlesmike** [comment]
> @charlesmike pls index [this](http://www.amihaiemil.com/rest/2016/06/03/using-google-recaptha-with-jax-rs.html) page

amihaiemil the given page does not seem to belong to the website hosted in this repo!

Make sure that the link starts with `http://` or `https://` followed by`owner.github.io/...` Do not use the CNAME or any other link, even if it redirects toa page from this repo. 

  If this condition is met and it still doesn't work please open an issue [here](https://github.com/amihaiemil/charles-github-ejb/issues).

**Comment by amihaiemil** [comment]
@charlesmike hi there

**Comment by charlesmike** [comment]
> @charlesmike hi there

Hi, @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format `owner.github.io` (or has a `gh-pages` branch) and the command is given by the repo's owner.

**Comment by amihaiemil** [comment]
@charlesmike pls index [this](http://www.amihaiemil.com/rest/2016/06/03/using-google-recaptha-with-jax-rs.html) page

**Comment by charlesmike** [comment]
> @charlesmike pls index [this](http://www.amihaiemil.com/rest/2016/06/03/using-google-recaptha-with-jax-rs.html) page

amihaiemil the given page does not seem to belong to the website hosted in this repo!

Make sure that the link starts with `http://` or `https://` followed by`owner.github.io/...` Do not use the CNAME or any other link, even if it redirects toa page from this repo. 

  If this condition is met and it still doesn't work please open an issue [here](https://github.com/amihaiemil/charles-github-ejb/issues).
