### ISSUE TITLE
Bug in checks order

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/charles-github-ejb#114]
Bug in the checks' execution order. As seen below, the index action should start, since I am repo owner and the repo has a gh-pages branch

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil the repository must not be a fork, you must own this repository.

**Comment by amihaiemil** [comment]
done
