### ISSUE TITLE
Unit tests for Command.java

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/charles-github-ejb#116]
More unit tests are needed for [Command.java](https://github.com/amihaiemil/charles-github-ejb/blob/master/charles-rest/src/main/java/com/amihaiemil/charles/github/Command.java)

**Comment by amihaiemil** [comment]
@charlesmike hello

**Comment by charlesmike** [comment]
> @charlesmike hello

Hi, @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format `owner.github.io` (or has a `gh-pages` branch) and the command is given by the repo's owner.

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly.

**Comment by amihaiemil** [comment]
@charlesmike online?

**Comment by charlesmike** [comment]
> @charlesmike online?

@amihaiemil sorry I do not understand you. See [this link](http://charles.amihaiemil.com/doc.html#commands) for more details.

**Comment by amihaiemil** [comment]
@charlesmike hi

**Comment by charlesmike** [comment]
> @charlesmike hi

Hi, @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format `owner.github.io` (or has a `gh-pages` branch) and the command is given by the repo's owner.

**Comment by amihaiemil** [comment]
Done
