### ISSUE TITLE
For index

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/charles-github-ejb#121]

**Comment by amihaiemil** [comment]
@charlesmike index pls

**Comment by charlesmike** [comment]
> @charlesmike index pls

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly.

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://ec2-54-68-83-8.us-west-2.compute.amazonaws.com:8080/charles-rest/api/logs/Action_8a46fa1b-bb6c-467e-bed9-e46ffa7db9de.log).

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil Some steps failed when precessing your command. See [logs](http://ec2-54-68-83-8.us-west-2.compute.amazonaws.com:8080/charles-rest/api/logs/Action_8a46fa1b-bb6c-467e-bed9-e46ffa7db9de.log) for details.

**Comment by amihaiemil** [comment]
@charlesmike index [this](http://charles.amihaiemil.com) page pls

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://charles.amihaiemil.com) page pls

@amihaiemil sorry I do not understand you. See [this link](http://charles.amihaiemil.com/doc.html#commands) for more details.

**Comment by amihaiemil** [comment]
@charlesmike index [this](http://charles.amihaiemil.com) page

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://charles.amihaiemil.com) page

@amihaiemil the given page does not seem to belong to the website hosted in this repo!

Make sure that the link starts with ``http://`` or ``https://`` followed by``yourusername.github.io/...`` Do not use the CNAME or any other link, even if it redirects toa page from this repo. 

  If this condition is met and it still doesn't work please open an issue [here](https://github.com/amihaiemil/charles-github-ejb/issues).

**Comment by amihaiemil** [comment]
@charlesmike index [this](http://amihaiemil.github.io/charles-github-ejb) page

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/charles-github-ejb) page

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://ec2-54-68-83-8.us-west-2.compute.amazonaws.com:8080/charles-rest/api/logs/Action_d6c3b51e-f6d7-4bf1-aa89-a54910541e40.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/charles-github-ejb) page

@amihaiemil Some steps failed when precessing your command. See [logs](http://ec2-54-68-83-8.us-west-2.compute.amazonaws.com:8080/charles-rest/api/logs/Action_d6c3b51e-f6d7-4bf1-aa89-a54910541e40.log) for details.

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://localhost:8080/charles-rest/api/logs/Action_5430c371-2060-4e63-a386-674c673555ad.log).

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil Some steps failed when precessing your command. See [logs](http://localhost:8080/charles-rest/api/logs/Action_5430c371-2060-4e63-a386-674c673555ad.log) for details.

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://ec2-54-68-83-8.us-west-2.compute.amazonaws.com:8080/charles-rest/api/logs/Action_0e61d411-7e15-4d40-9af8-1ec71ad4b578.log).

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil Some steps failed when precessing your command. See [logs](http://ec2-54-68-83-8.us-west-2.compute.amazonaws.com:8080/charles-rest/api/logs/Action_0e61d411-7e15-4d40-9af8-1ec71ad4b578.log) for details.

**Comment by amihaiemil** [comment]
@charlesmike index pls

**Comment by charlesmike** [comment]
> @charlesmike index pls

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://ec2-54-68-83-8.us-west-2.compute.amazonaws.com:8080/charles-rest/api/logs/Action_3f7b3b4c-faf4-40ea-a162-bf83edb652e0.log).

**Comment by charlesmike** [comment]
> @charlesmike index pls

@amihaiemil Some steps failed when precessing your command. See [logs](http://ec2-54-68-83-8.us-west-2.compute.amazonaws.com:8080/charles-rest/api/logs/Action_3f7b3b4c-faf4-40ea-a162-bf83edb652e0.log) for details.

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://ec2-54-68-83-8.us-west-2.compute.amazonaws.com:8080/charles-rest/api/logs/Action_a4e3c0a8-59d1-4359-9997-558a157e7abb.log).

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil Some steps failed when precessing your command. See [logs](http://ec2-54-68-83-8.us-west-2.compute.amazonaws.com:8080/charles-rest/api/logs/Action_a4e3c0a8-59d1-4359-9997-558a157e7abb.log) for details.

**Comment by amihaiemil** [comment]
@charlesmike index pls

**Comment by charlesmike** [comment]
> @charlesmike index pls

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://ec2-54-68-83-8.us-west-2.compute.amazonaws.com:8080/charles-rest/api/logs/Action_68dd41ef-3e8f-4724-8bcd-d4b016d8b698.log).

**Comment by charlesmike** [comment]
> @charlesmike index pls

@amihaiemil Some steps failed when precessing your command. See [logs](http://ec2-54-68-83-8.us-west-2.compute.amazonaws.com:8080/charles-rest/api/logs/Action_68dd41ef-3e8f-4724-8bcd-d4b016d8b698.log) for details.

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://ec2-54-68-83-8.us-west-2.compute.amazonaws.com:8080/charles-rest/api/logs/Action_0a57af05-6e9e-485c-b452-dc5c144fab05.log).

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil Some steps failed when precessing your command. See [logs](http://ec2-54-68-83-8.us-west-2.compute.amazonaws.com:8080/charles-rest/api/logs/Action_0a57af05-6e9e-485c-b452-dc5c144fab05.log) for details.

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index


@amihaiemil sorry I do not understand you. See [this link](http://charles.amihaiemil.com/doc.html#commands) for more details.

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://ec2-54-68-83-8.us-west-2.compute.amazonaws.com:8080/charles-rest/api/logs/Action_e1868d9d-df05-4a34-aee5-b8f316a5f7d4.log).

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil Some steps failed when precessing your command. See [logs](http://ec2-54-68-83-8.us-west-2.compute.amazonaws.com:8080/charles-rest/api/logs/Action_e1868d9d-df05-4a34-aee5-b8f316a5f7d4.log) for details.

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://localhost:8080/charles-rest/api/logs/Action_0da23cf6-9dcb-4397-94aa-689df106f9a0.log).

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil Some steps failed when precessing your command. See [logs](http://localhost:8080/charles-rest/api/logs/Action_0da23cf6-9dcb-4397-94aa-689df106f9a0.log) for details.

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://localhost:8080/charles-rest/api/logs/Action_bce50cef-12d9-4dab-b800-a05d5df2f29c.log).

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil Some steps failed when precessing your command. See [logs](http://localhost:8080/charles-rest/api/logs/Action_bce50cef-12d9-4dab-b800-a05d5df2f29c.log) for details.

**Comment by amihaiemil** [comment]
@charlesmike index pls

**Comment by charlesmike** [comment]
> @charlesmike index pls

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://localhost:8080/charles-rest/api/logs/Action_7236bb65-b444-4597-ade2-b91f3ef25aaa.log).

**Comment by charlesmike** [comment]
> @charlesmike index pls

@amihaiemil Some steps failed when precessing your command. See [logs](http://localhost:8080/charles-rest/api/logs/Action_7236bb65-b444-4597-ade2-b91f3ef25aaa.log) for details.

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://localhost:8080/charles-rest/api/logs/Action_c1f10727-af6f-469e-9108-f20b50dc5470.log).

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil Some steps failed when precessing your command. See [logs](http://localhost:8080/charles-rest/api/logs/Action_c1f10727-af6f-469e-9108-f20b50dc5470.log) for details.

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://localhost:8080/charles-rest/api/logs/Action_6514c8af-bcfa-4ac2-9d65-b9f9a1bdf344.log).

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil Some steps failed when precessing your command. See [logs](http://localhost:8080/charles-rest/api/logs/Action_6514c8af-bcfa-4ac2-9d65-b9f9a1bdf344.log) for details.

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://localhost:8080/charles-rest/api/logs/Action_c87eb3d6-945b-4102-a519-e5d60ac6e55e.log).

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil Some steps failed when precessing your command. See [logs](http://localhost:8080/charles-rest/api/logs/Action_c87eb3d6-945b-4102-a519-e5d60ac6e55e.log) for details.

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://localhost:8080/charles-rest/api/logs/Action_72cf8061-328d-4d4b-900d-b43067c23a9c.log).

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil Some steps failed when precessing your command. See [logs](http://localhost:8080/charles-rest/api/logs/Action_72cf8061-328d-4d4b-900d-b43067c23a9c.log) for details.

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://ec2-54-68-83-8.us-west-2.compute.amazonaws.com:8080/charles-rest/api/logs/Action_62ffcb2f-a4a1-4ef8-8350-10e1684a981c.log).

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil Some steps failed when precessing your command. See [logs](http://ec2-54-68-83-8.us-west-2.compute.amazonaws.com:8080/charles-rest/api/logs/Action_62ffcb2f-a4a1-4ef8-8350-10e1684a981c.log) for details.

**Comment by amihaiemil** [comment]
@charlesmike hello there

**Comment by charlesmike** [comment]
> @charlesmike hello there

Hi, @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format `owner.github.io` (or has a `gh-pages` branch) and the command is given by the repo's owner.

**Comment by amihaiemil** [comment]
@charlesmike test

**Comment by charlesmike** [comment]
> @charlesmike test

@amihaiemil sorry I do not understand you. See [this link](http://charles.amihaiemil.com/doc.html#commands) for more details.

**Comment by amihaiemil** [comment]
@charlesmike hi
