### ISSUE TITLE
Index doesn't work for this repo

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/charles-github-ejb#144]
See the generated logs bellow for details. Find the issue and fix it.

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/feb4cb91-c657-4c20-991f-8085a331a86f.log).

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil Some steps failed when precessing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/feb4cb91-c657-4c20-991f-8085a331a86f.log) for details.

**Comment by amihaiemil** [comment]
@charlesmike hi

**Comment by charlesmike** [comment]
> @charlesmike hi

Hi @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format ``owner.github.io`` (or has a ``gh-pages`` branch) and the command is given by the repo's owner.

More on commands [here](http://charles.amihaiemil.com/doc.html#commands).

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/aed9957f-3109-405c-b27d-c8b19be16bbc.log).

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil Some steps failed when precessing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/aed9957f-3109-405c-b27d-c8b19be16bbc.log) for details.

**Comment by amihaiemil** [comment]
@charlesmike hello

**Comment by charlesmike** [comment]
> @charlesmike hello

Hi @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format ``owner.github.io`` (or has a ``gh-pages`` branch) and the command is given by the repo's owner.

More on commands [here](http://charles.amihaiemil.com/doc.html#commands).

**Comment by amihaiemil** [comment]
@charlesmike index pls

**Comment by charlesmike** [comment]
> @charlesmike index pls

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/a3444a46-a244-4f32-b644-d467bfdea7f7.log).

**Comment by charlesmike** [comment]
> @charlesmike index pls

@amihaiemil Some steps failed when precessing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/a3444a46-a244-4f32-b644-d467bfdea7f7.log) for details.

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/7772f725-a606-4bd8-bd58-1e45d5b252b6.log).

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil Some steps failed when precessing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/7772f725-a606-4bd8-bd58-1e45d5b252b6.log) for details.

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/2c50ec55-5535-40c0-9ade-84a60733ada9.log).

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil Some steps failed when precessing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/2c50ec55-5535-40c0-9ade-84a60733ada9.log) for details.

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/f7dd3549-0ac9-410b-8699-f05082d74985.log).

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil Some steps failed when precessing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/f7dd3549-0ac9-410b-8699-f05082d74985.log) for details.

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/cf5ef5a1-aa04-47e0-ab36-b80098b95449.log).

**Comment by charlesmike** [comment]
There was an error when processing your command. [Here](http://charles.amihaiemil.com/logs.html?log=/cf5ef5a1-aa04-47e0-ab36-b80098b95449.log) are the logs.

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/3bf12fe7-ef3d-4b66-acfa-d2abdd7b8ab3.log).

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil Some steps failed when precessing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/3bf12fe7-ef3d-4b66-acfa-d2abdd7b8ab3.log) for details.

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/c13df1e3-c75e-4e33-87e5-64d14cfe2850.log).

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil Some steps failed when precessing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/c13df1e3-c75e-4e33-87e5-64d14cfe2850.log) for details.

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/da4420ad-3f43-4036-b7ce-70fcb68e2abe.log).

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil Some steps failed when precessing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/da4420ad-3f43-4036-b7ce-70fcb68e2abe.log) for details.

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/cc701098-72a1-4401-8bc4-0b7b06174cae.log).

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil Some steps failed when precessing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/cc701098-72a1-4401-8bc4-0b7b06174cae.log) for details.

**Comment by amihaiemil** [comment]
the initial errors were fixed. Now it's #162
