### ISSUE TITLE
Step.perform() -> Step.perform(Command, Logger)

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/charles-github-ejb#155]
Class Brain is growing bigger and bigger with quite long methods and duplicated code.
It should be broken down in more components and maybe made imutable. 

**Idea**: ``Brain`` might work with ``Knowledge``s or ``Understanding``s. These would be responsible for returning the Steps to be executed. In other words:  "the agent (brain) has **knowledge** of how to index a site, index a page, delete an index etc"

**Comment by amihaiemil** [comment]
This is postponed to version ``1.1.0``, since we should publish the release soon and do not have time to keep going back and refactor code. Also, no more actions/commands steps will be implemented until then.

**Comment by amihaiemil** [comment]
@charlesmike hello ... are you off regex?

**Comment by charlesmike** [comment]
> @charlesmike hello ... are you off regex?

Hi @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format ``owner.github.io`` (or has a ``gh-pages`` branch) and the command is given by the repo's owner.

More on commands [here](http://charles.amihaiemil.com/doc.html#commands).

**Comment by amihaiemil** [comment]
The Command and Logger should be passed as params in the perform(...) method to:

1) make the building of the Steps pyramid easier and more readable
2) make sure all the steps in the pyramid work on the same command and with the same logger (right now, you can add any steps on top of eachother, and each step may work with a different command)
