### ISSUE TITLE
Russian language

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/charles-github-ejb#174]
Let's teach it russian

**Comment by amihaiemil** [comment]
@salikjan Think you could have a look over it when you have time? See how the Language class is used and those properties files. It's a nice chance to learn this part of the project :) 

Have a look, break it down into multiple puzzles (e.g. one for the property files, one for Russian class + usage in Brain and one for unit tests?)

Any questions, just ask :D

**Comment by amihaiemil** [comment]
@salikjan here, for starters, just have a look over the 2 properties files and see if they could be translated into russian, while respecting the same regexes. Let me know what you think :D

**Comment by salikjan** [comment]
When i break down an issie into a few puzzles shoud i mark this somewhere on git or just in mind?
Files can be easily tranlsated to russian.
As i understand files shoud be commands_ru.properties, responses_en.properties?

**Comment by amihaiemil** [comment]
@salikjan yes exactly, the 2 new files should be ``commands_ru.properties`` and ``responses_ru.properties``

You add each puzzle in the code as a ``@todo``. Such a todo will usually be located in a javadoc (it could also be a comment in an xml file for instance). You should put the todo in the code, closest to where the change should happen.

[Here](https://github.com/opencharles/charles-rest/blob/master/src/main/java/com/amihaiemil/charles/rest/RestApplication.java#L36) is an example

The format of a todo is: 

```
@todo #parent_issue_number:30m/DEV Explanation of the puzzle here, which will most likely
 be on multiple lines. Should be explanatory enough to get the job done, or point out an issue
 where the assignee can find more details.
```

Also, notice the spacing (new lines have a space in front)

![image](https://cloud.githubusercontent.com/assets/6305156/21802851/1bde52fa-d730-11e6-934f-b82dba670682.png)


For the puzzles that you will leave in the code now, parent_issue_number is 174 (this issue).
Estimation can also be 1h if 30m is not enough. But usually, 30m is ok, since that puzzle can as well be broken down in multiple puzzles.

**Comment by salikjan** [comment]
Ok. But where in code i should place @todo in the case of properties files which are not exist?

**Comment by amihaiemil** [comment]
@salikjan In this case I would say above the Language class.

More puzzles can be in the same place, one under the other.
I say this because in the Language class there will also be the todo for implementing and unit testing Russian class.

**Comment by amihaiemil** [comment]
@salikjan can you pls make another PR, adding spaces at the beginning of each new line in the todos from Language? Also, put back the puzzle for translating responses.properties as well. A task should be opened, and I'm going to assign it to you :D

**Comment by amihaiemil** [comment]
@salikjan Also, it seems that character encoding will be fun, but we'll see :D

**Comment by salikjan** [comment]
@amihaiemil i thought about it )) may be we should negotiate the codepage? koi8-r, win-1251 or unicode so i could set it in my ide or external editor as like as notepad++

**Comment by salikjan** [comment]
@amihaiemil now utf-8 is set in idea

**Comment by amihaiemil** [comment]
@salikjan well, for now, just make that PR when you have time (to fix the puzzles) and let's close this issue. We'll talk later. I think UTF-8 should do the trick? Not sure, I'll have to study it a bit

**Comment by amihaiemil** [comment]
@salikjan ``koi8-r`` worked for me, in Eclipse. I set the file encoding to that and now they seem to be displayed alright. I mean, I guess. They seem like paitings to me, haha :))

**Comment by salikjan** [comment]
I have translated 1/3 of responses properties file. To be continued tomorrow ))

**Comment by amihaiemil** [comment]
@salikjan Sure, thank you :D 

Just a note: a puzzle is intended to delegate the task to someone else. So you add a puzzle in the code not for yourself to keep track of your work, but for someone else to take it up later. Well, in this particular case, you would have done it anyway, since you're the only russian speaker. But if there was someone else, the puzzle might have been taken up by them.

I added this, because it gave me the impression that you added the puzzle in order for you to track your work. You also said something about "keeping the puzzles in mind" :D

**Comment by salikjan** [comment]
What is the attitude in responses should be when I meet "you" in text. You? or thou? Beacuse in russian two words used for this. Polite You and not polite Thou.

**Comment by amihaiemil** [comment]
@salikjan casual, so not necessarily polite, is ok. "thou" should be fine. I doubt anyone will ever get upset about this. Those people do not use Github, for sure :))

**Comment by salikjan** [comment]
ok )) what about delegating? i should tell you that I've finished working on issue and you can delegate issue to someone else?
Or do it by my own?

**Comment by amihaiemil** [comment]
@salikjan You simply leave the puzzles in the code, and when the branch is merged, one issue for each puzzle should be opened automatically (by [0pdd](https://www.github.com/0pdd)). Now one issue should have been opened, since you let a todo, but I think it didn't work because it misses the space at the beginning of the new sentence (I'll add it).

So, when you add a puzzle, you're basically saying "I let this part of the task to someone else".
When the issue gets created, yes, I'll assign the task to someone or maybe do it myself.

**Comment by amihaiemil** [comment]
@salikjan I'm closing this since the property files are done. Btw, you are now listed as a contributor on the site as well: http://charles.amihaiemil.com/
