### ISSUE TITLE
Fix/missing unit test AwsHttpHeaders

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/charles-github-ejb#177]
[This](https://github.com/opencharles/charles-rest/blob/master/src/test/java/com/amihaiemil/charles/aws/AwsHttpHeadersTestCase.java) is the unit tests class for [AwsHttpHeaders](https://github.com/opencharles/charles-rest/blob/master/src/main/java/com/amihaiemil/charles/aws/AwsHttpHeaders.java).

There is a problem with unit test performsRequest(), because it checks for 2 things:
  1) the request was performed 
  2) the headers are added

This test should be split in 2 unit tests: 
  - remove from it the headers part, only leave the actual perform check
  - write another unit test, named addsHeaders() in which to check if a map of headers is added to the base requst. Make sure the base request has some initial headers too, to see if AwsHttpHeaders doesn't override the existing ones,

**Comment by amihaiemil** [comment]
@brinstong Can you do this? AwsHttpHeaders is a simple decorator, and you should see form the other unit tests how to use FakeAwsHttpRequest instead of an actual base request.

Make sure ``mvn clean install`` passes before making a PR.
Any questions you might have, please ask here.

Don't forget to do the changes on branch 177 (named after this ticket)

**Comment by amihaiemil** [comment]
@brinstong Have you done anything here or did you change your mind? Should I assign someone else? :D

**Comment by amihaiemil** [comment]
@SherifWaly Can you take this up when you have some time? Keep in mind that you don't need to get the whole webapp running on a server. Just make sure the test and maven build ``mvn clean install`` passes after you make the changes. 

Also, changes should be done on a separate branch, named 177 (after the ticket number). **Master branch is read-only**. When you're done, make a PR.

**Comment by SherifWaly** [comment]
@amihaiemil mvn clean command passes but mvn install gives compilation error. Could you help me in solving this problem?

**Comment by amihaiemil** [comment]
@SherifWaly I made the review of your PR - I have 3 comments there :) 

Also, I think you mean that the ``build is failing``, not that there are ``compilation errors``? 
The build can fail mainly because of failed unit tests or other reasons, such as code quality failure.
But it is quite impossible to have compilation failures - first of all, you would see them in your IDE. 

Whatever it was, it seems to be fixed anyway, since all the CI checks passed for the PR.

**Comment by SherifWaly** [comment]
@amihaiemil  There were compilations errors but I fixed it by installing some missing issues with the JDK :)

**Comment by amihaiemil** [comment]
@SherifWaly thanks! :)
