### ISSUE TITLE
Brain.java:61-63: After Russian language is done and teste...

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/charles-github-ejb#184]
The puzzle `181-ca416da0` in `src/main/java/com/amihaiemil/charles/github/Brain.java` (lines 61-63) has to be resolved: After Russian language is done and tested, let's start using it. It should be added bellow, right after English and everything should work after that.

The [puzzle](http://www.yegor256.com/2009/03/04/pdd.html) was created by Mihai Emil Andronache on 19-Jan-17. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by amihaiemil** [comment]
This issue is obsolete now, as we will refactor the brain. It will only speak english, and it won't work with regexes anymore as they are hard to mantain and explain. We'll keep it simple: english and containing words instead or regex...

**Comment by 0pdd** [comment]
The puzzle `181-ca416da0` has disappeared from the source code, that's why I closed this issue.
