### ISSUE TITLE
English.java:33-35: Implement and unit test Language class R...

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/charles-github-ejb#186]
The puzzle `174-2ae6a13d` in `src/main/java/com/amihaiemil/charles/github/English.java` (lines 33-35) has to be resolved: Implement and unit test Language class Russian, following the model of this class and its unit tests. The class should use the commands_ru and responses_ru properties files.

The [puzzle](http://www.yegor256.com/2009/03/04/pdd.html) was created by Mihai Emil Andronache on 19-Jan-17. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by amihaiemil** [comment]
This issue is obsolete now, as we will refactor the brain. It will only speak english, and it won't work with regexes anymore as they are hard to mantain and explain. We'll keep it simple: english and containing words instead or regex...

**Comment by 0pdd** [comment]
The puzzle `174-2ae6a13d` has disappeared from the source code, that's why I closed this issue.
