### ISSUE TITLE
Update charles lib version

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/charles-github-ejb#188]
Charles 1.1.1 is out containing important bug fixes. Let's update the version and deploy.

**Comment by amihaiemil** [comment]
@charlesmike hi there

**Comment by charlesmike** [comment]
> @charlesmike hi there

Hi @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format ``owner.github.io`` (or has a ``gh-pages`` branch) and the command is given by the repo's owner.

More on commands [here](http://charles.amihaiemil.com/doc.html#commands).
