### ISSUE TITLE
A class for each system property

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/charles-github-ejb#199]
We read a few system properties in the aws layer. 
Let's create classes for each of them and correct the unit tests, according to [this](http://www.amihaiemil.com/2017/02/24/each-system-property-a-class.html) article

**Comment by amihaiemil** [comment]
@SherifWaly Want to start this? It's quite a lot of changes, but we use PDD.

For starters, I would add interfaces ``EsEndpoint``, ``Region``, ``AccessKeyId``, and `` SecretKey`` (these are 4 system properties that are read in the AWS logic). All of these 4 interfaces should extend interface ``SystemProperty`` which has the method ``String read()``. In the package ``com.amihaiemil.charles.aws``

What do you think?

**Comment by SherifWaly** [comment]
@amihaiemil Ok I will try to understand this task and start it.

**Comment by amihaiemil** [comment]
@SherifWaly Just read that article and add those interfaces -- no need to start using them in the code yet. I'll start with them and you'll see :D 

And leave a puzzle in the code, for this task to be continued

**Comment by amihaiemil** [comment]
@SherifWaly By the way, the build on this project is simply ``mvn clean install`` (no checkstyle because it wasn't added from the beginning and now it's a mess... I'll have to fix it someday... see [here](https://github.com/opencharles/charles-rest/issues/166))

**Comment by amihaiemil** [comment]
@SherifWaly btw, you are now listed as a contributor here: http://charles.amihaiemil.com

**Comment by SherifWaly** [comment]
@amihaiemil I'm happy to know that :D Thanks Mihai!
