### ISSUE TITLE
AbstractSystemProperty.java:34-35: Add fake implementation for the 4...

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/charles-github-ejb#205]
The puzzle `201-af20c932` in [`src/main/java/com/amihaiemil/charles/aws/AbstractSystemProperty.java`](https://github.com/opencharles/charles-rest/blob/master/src/main/java/com/amihaiemil/charles/aws/AbstractSystemProperty.java) (lines 34-35) has to be resolved: Add fake implementation for the 4 SystemProperty interfaces to use them in testing.

The puzzle was created by sherif on 29-Mar-17. 

Estimate: 15 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html).

**Comment by amihaiemil** [comment]
@charlesmike hello

**Comment by charlesmike** [comment]
> @charlesmike hello

Hi @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format ``owner.github.io`` (or has a ``gh-pages`` branch) and the command is given by the repo's owner.

More on commands [here](http://charles.amihaiemil.com/doc.html#commands).

**Comment by missourpro** [comment]
@charlesmike hello there!

**Comment by charlesmike** [comment]
> @charlesmike hello there!

Hi @missourpro! I can help you index your Github-hosted website, provided that the repository name respects the format ``owner.github.io`` (or has a ``gh-pages`` branch) and the command is given by the repo's owner.

More on commands [here](http://charles.amihaiemil.com/doc.html#commands).

**Comment by 0pdd** [comment]
The puzzle `201-af20c932` has disappeared from the source code, that's why I closed this issue.
