### ISSUE TITLE
Link to docs in case of unkown command

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/charles-github-ejb#22]
There should be a page documenting the commands that it understands.

**Comment by amihaiemil** [comment]
@charlesmike doesn't know many commands

**Comment by charlesmike** [comment]
@amihaiemil, sorry, I do not understand you. See [this link](#) for more details.

**Comment by amihaiemil** [comment]
@charlesmike hello there!

**Comment by charlesmike** [comment]
Hi, @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format ``author.github.io`` and the command is given by the repo's author.

**Comment by amihaiemil** [comment]
@charlesmike, hi!!!

**Comment by charlesmike** [comment]
Hi, @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format ``author.github.io`` and the command is given by the repo's author.

**Comment by amihaiemil** [comment]
@charlesmike hello there!!

**Comment by amihaiemil** [comment]
@charlesmike hi

**Comment by amihaiemil** [comment]
done
