### ISSUE TITLE
Use the AbstractSystemProperties in the aws layer

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/charles-github-ejb#230]
We have some system properties implemented, which encapsulate the logic related to reading/setting system props. let's use those in the aws layer, they would simplify the tests a lot.

**Comment by pavanchowdary007** [comment]
Hi @amihaiemil. I am searching for connecting (Examples ) api for Amazon Elastic Search   . I know this is not right place to ask this question . But I thought u can help me for this . ThanQ

**Comment by amihaiemil** [comment]
@pavanchowdary007 Hello there! You can communicate with AWS Elastic Search by making HTTP requests to the REST API.

The trouble is, if you make your own HTTP requests, you need to implement all the [signing logic](http://docs.aws.amazon.com/general/latest/gr/signing_aws_api_requests.html), which is quite complicated.

I use classes from aws-java-sdk, in order to build my own requests, since they provide also the signing logic. If it weren't for that signing logic, you could have used any HTTP client... 

See how I did it here: http://www.amihaiemil.com/2017/02/18/decorators-with-tunnels.html
I talked with one of aws-java-sdk's maintainers and he told me that I am not even supposed to see those classes... so you can imagine how well designed is that SDK... but yes it seems to work fine for me :D 

For other AWS services, you could maybe study the SDK and use it directly. It's hard, but doable. However, for ElasticSearch, the maintainer told me that the SDK only provides functionalities for the administrative part of the ElasticSearch instance (scaling, restarting etc), not for the functionality of ES itself, like search index etc.

Just today I changed the AWS layer from this app (I pulled out and abstractized some system properties), so it's just a bit different now from the blog post, but the idea is still the same.

If you have any other questions, feel free to ask!

Cheers,
Mihai

**Comment by amihaiemil** [comment]
@pavanchowdary007 I'm going to close this issue since it is resolved. If you have any other questions, feel free to ask them on the blog or open another issue in this repo :D
