### ISSUE TITLE
Switch from PhantomJs to Headless Chrome

### ISSUE THREAD

**Issue by g4s8** [amihaiemil/charles-github-ejb#254]
I tried to index site, but [some steps failed](https://github.com/g4s8/g4s8.github.io/issues/1#issuecomment-327008090). I restarted with same command and got same error.
BTW @charlesmike posted link to logs, but I didn't find them on page: http://charles.amihaiemil.com/logs.html?log=/887c5b90-1aa5-46e8-9357-3f692e37badc.log

**Comment by amihaiemil** [comment]
@g4s8 index site sometimes fails bc phantomjs and selenium are quite volatile... trouble when navigating. I'll migrate it to headless chrome as soon as I have some time. In the meantime, try index sitemap, I never had issues with that one.

The logs should display fine, never had issue with them either. Can you maybe open an issue about that, with the link that doesnt work?

**Comment by amihaiemil** [comment]
@g4s8 apparently, AWS Free Tier is so cheap, that the server's memory is occupied with log files...:
```
  java.io.IOException: No space left on device
````

cleaning up now...

That's why the logs didn't show, the file couldn't even be created...

**Comment by amihaiemil** [comment]
@g4s8 cleaned and restarted, it should work fine now. Even index site should work for your blog, since it has a few pages only. If not, index sitemap or index page.  Also, the logs should be created and displayed :)

**Comment by g4s8** [comment]
@amihaiemil thanks, now I can read logs. Index sitemap command also working fine.
Here new link to logs with `index site` failing: http://charles.amihaiemil.com/logs.html?log=/f6754fb4-baec-467a-b10b-d0fc674c8d62.log

**Comment by amihaiemil** [comment]
Yes, it's definetely phantom + selenium, I had the same errors
