### ISSUE TITLE
AmazonEsRepository.java:57-58: Implement the delete page knowledge....

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/charles-github-ejb#260]
The puzzle `250-3323e69b` (from #250) in [`src/main/java/com/amihaiemil/charles/aws/AmazonEsRepository.java`](https://github.com/opencharles/charles-rest/blob/master/src/main/java/com/amihaiemil/charles/aws/AmazonEsRepository.java) (lines 57-58) has to be resolved: "Implement the delete page knowledge. We have the repo method and unit test for it. Continue with the language, knowledge and steps."

The puzzle was created by amihaiemil on 05-Sep-17. 

Estimate: 60 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by amihaiemil** [comment]
done and waiting release

**Comment by amihaiemil** [comment]
@charlesmike please delete [this](http://opencharles.github.io/charles-rest/index.html) page

**Comment by charlesmike** [comment]
> @charlesmike please delete [this](http://opencharles.github.io/charles-rest/index.html) page

@amihaiemil Some steps failed when processing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/d0181af5-5eda-444c-8654-eb488275935a.log) for details.
Try again and if the error persists please, open an [issue](https://github.com/opencharles/charles-rest/issues/new).
