### ISSUE TITLE
AmazonEsRepository.java:59-60: Rename this class to Index (since...

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/charles-github-ejb#261]
The puzzle `250-d7d97575` (from #250) in [`src/main/java/com/amihaiemil/charles/aws/AmazonEsRepository.java`](https://github.com/opencharles/charles-rest/blob/master/src/main/java/com/amihaiemil/charles/aws/AmazonEsRepository.java) (lines 59-60) has to be resolved: "Rename this class to Index (since that's what it is), and remove AmazonEsSearch class, moving the search method here"

The puzzle was created by amihaiemil on 05-Sep-17. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by amihaiemil** [comment]
Renamed to ElasticSearch and AmazonElasticSearch, instead of Index
