### ISSUE TITLE
enable HTTPS

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/charles-github-ejb#269]
Use let's encrypt to get a certificate for glassfish:
https://community.letsencrypt.org/t/how-do-i-generate-the-lets-encrypt-certificate-and-key-on-my-own-device-more-info-inside/27510/6

**Comment by amihaiemil** [comment]
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/SSL-on-an-instance.html

Step 2: Obtain a CA-signed Certificate

**Comment by amihaiemil** [comment]
@comdor hello

**Comment by zoeself** [comment]
@amihaiemil Hi there! I'm only version `0.0.2`, so I can't do much yet. Follow me and [my website](http://comdor.co) for updates on the next version.

**Comment by amihaiemil** [comment]
@comdor hello

**Comment by zoeself** [comment]
@amihaiemil Hi there! I'm only version `0.0.2`, so I can't do much yet. Follow me and [my website](http://comdor.co) for updates on the next version.
