### ISSUE TITLE
Mixed content on https page

### ISSUE THREAD

**Issue by g4s8** [amihaiemil/charles-github-ejb#275]
Charles script could not be loaded from https page.

Here is my script tag:
```html
<script
  type="text/javascript"
  id="charlesscript"
  repo="g4s8/g4s8.github.io"
  src="http://www.amihaiemil.com/js/charles/charles.min.js">
</script>
```

Firefox error:
> Blocked loading mixed active content “http://www.amihaiemil.com/js/charles/charles.min.js”

Chrome error:
> Mixed Content: The page at 'https://g4s8.github.io/' was loaded over HTTPS, but requested an insecure script 'http://www.amihaiemil.com/js/charles/charles.min.js'. This request has been blocked; the content must be served over HTTPS.

I can't change `http://www.amihaiemil.com` to `https://www.amihaiemil.com` because ssl cert on `www.amihaiemil.com` is not valid.

I think this script and other resources (such as css, images) can be served on `https://webapps.amihaiemil.com`.

**Comment by amihaiemil** [comment]
@g4s8 yes, you are right, I'll look into it. But only on Monday, I'm afraid, I dont have my laptop this weekend. Until this is fixed, you can download the script yourself and add it on your site :)

**Comment by amihaiemil** [comment]
I'll try to fix it tomorrow, too, if I can get my hands on a laptop with an SSH client

**Comment by amihaiemil** [comment]
@g4s8 done; I moved all the resources under the https domain, including the CSS and images. Just change the src attribute to https://webapps.amihaiemil.com/resources/charles/charles.min.js and it should work fine. 

Please close this issue if it works :D

**Comment by g4s8** [comment]
@amihaiemil many thanks! It's working now :+1:
