### ISSUE TITLE
Add charles-rest here

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/charles-github-ejb#31]
Add project charles-rest to this repository and wrap charles-github-ejb inside it.

**Comment by amihaiemil** [comment]
@charlesmike hi there!!!

**Comment by charlesmike** [comment]
Hi, @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format `author.github.io` and the command is given by the repo's author.

**Comment by amihaiemil** [comment]
done
