### ISSUE TITLE
Propagate Action Logger

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/charles-github-ejb#37]
Propagate an Action's Logger to other methods like `Brain.understand` in order to log the Action in more detail.

**Comment by amihaiemil** [comment]
@charlesmike hello

**Comment by charlesmike** [comment]
> @charlesmike hello

Hi, @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format ``author.github.io`` and the command is given by the repo's author.

**Comment by amihaiemil** [comment]
@charlesmike doesn't understand much

**Comment by charlesmike** [comment]
> @charlesmike doesn't understand much

@amihaiemil, sorry, I do not understand you. See [this link](#) for more details.

**Comment by amihaiemil** [comment]
done

**Comment by amihaiemil** [comment]
@amihaiemil hi
