### ISSUE TITLE
Bug in Brain.understand

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/charles-github-ejb#43]
Currently it loops through all the Languages, meaning that if the command is not written in the last Language in the list, it will not be understood. The iteration should stop once the command is understood

**Comment by amihaiemil** [comment]
@charlesmike hi...

**Comment by charlesmike** [comment]
> @charlesmike hi...

Hi, @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format ``author.github.io`` and the command is given by the repo's author.
