### ISSUE TITLE
 Pull out IndexSiteSteps.sendFollowupMessage

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/charles-github-ejb#73]
The logic from that method should be pulled out into `FollowupMessage` class. Also, if mail send fails, then a comment should be posted to Github.

**Comment by amihaiemil** [comment]
Decided to remove `SendEmail` logic for now and just respond only via Github comment. Mainly because it introduces too much complexity/configs and risk for failure.

**Comment by amihaiemil** [comment]
`FollowupMessage` not needed for now

**Comment by amihaiemil** [comment]
@charlesmike pls index

**Comment by charlesmike** [comment]
> @charlesmike pls index

@amihaiemil Index site action started. I'll let you know of the progress...

**Comment by charlesmike** [comment]
> @charlesmike pls index

@@amihaiemil the repository's name must match the format `owner.github.io` or it must have a project website on branch `gh-pages`

**Comment by charlesmike** [comment]
> @charlesmike pls index

@amihaiemil Action finished successfully. See [logs](http://localhost:8080/charles/api/logs/b0d45c05-be2c-4561-8626-f15422e17089.log) the logs for more details. 
 If you notice any inexplicable errors, please open an issue <a href="https://github.com/amihaiemil/charles-github-ejb">here</a>
